//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graphics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graphics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radeon Ares HD5870X2 4GB
        ///Radeon HD5970 4GB
        ///Radeon HD5970 2GB
        ///Geforce GTX 580 1536MB
        ///Geforce GTX 570 1280MB
        ///Radeon HD6970 2GB
        ///Geforce GTX 480 1536MB
        ///Radeon HD6950 2GB
        ///Geforce GTX 295 1792MB
        ///Radeon HD4870X2 2GB
        ///Radeon HD5870 2GB
        ///Radeon HD5870 1GB
        ///Geforce GTX 470 1280MB
        ///Radeon HD6870 1GB
        ///Radeon HD5850 1GB
        ///Radeon HD4850X2 2GB
        ///Radeon HD6850 1GB
        ///Geforce GTX 460 2GB
        ///Geforce GTX 285 2GB
        ///Geforce GTX 460 1GB
        ///Geforce GTX 465 1GB
        ///Geforce GTX285 1GB
        ///Radeon HD4850X2 1GB
        ///Geforce GTX 460 768MB
        ///Radeo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DesktopGraphicsCardsByRank {
            get {
                return ResourceManager.GetString("DesktopGraphicsCardsByRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA	GeForce GTX 470M SLI
        ///NVIDIA	GeForce GTX 480M SLI
        ///AMD	Radeon HD 6970M Crossfire	Blackcomb XT
        ///NVIDIA	GeForce GTX 460M SLI
        ///ATI	Mobility Radeon HD 5870 Crossfire	Broadway-XT
        ///NVIDIA	GeForce GTX 485M
        ///NVIDIA	GeForce GTX 285M SLI
        ///AMD	Radeon HD 6970M	Blackcomb XT
        ///NVIDIA	GeForce GTX 280M SLI
        ///AMD	Radeon HD 6950M	Blackcomb Pro
        ///ATI	Mobility Radeon HD 4870 X2
        ///NVIDIA	GeForce GTX 470M
        ///NVIDIA	GeForce GTX 480M
        ///NVIDIA	GeForce GTX 260M SLI
        ///NVIDIA	GeForce 9800M GTX SLI
        ///ATI	Mobility Radeon HD 5870	Broadway- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LaptopGraphicsCardsByRank {
            get {
                return ResourceManager.GetString("LaptopGraphicsCardsByRank", resourceCulture);
            }
        }
    }
}
